
server:
  port: 0
  servlet:
    context-path: '/pessoas/'

spring:
  application:
    name: pessoas
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/pessoasdb?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka